# -*- coding: utf-8 -*-
"""BCIS 466 Semester Final Project - Rudra Chevdawala.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mny3m0su0TIYSMCLS6bCqp38iYOO4I-c
"""

# Adult Census Income Classification
# Predicting whether someone earns >$50K/year
# Dataset: UCI Adult Census Income
# Name: Rudra Chevdawala
# Date: 2026

# Install & Import
!pip install ucimlrepo

from ucimlrepo import fetch_ucirepo
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score, roc_curve

import warnings
warnings.filterwarnings('ignore')

# 1. Load the Dataset

adult = fetch_ucirepo(id=2)

X = adult.data.features
y = adult.data.targets

# Combine features and target into one dataframe
df = pd.concat([X, y], axis=1)
df.columns = list(X.columns) + ["income"]


print("Dataset Shape:", df.shape)
print(df.head())

# 2. Explore the Data

print("\nMissing values:")
print(df.isnull().sum())


# Fixing Income Labels
df["income"] = df["income"].str.strip().str.replace(".", "", regex=False)

# Plot 1: Income Class Cistribution
plt.figure(figsize=(6,7))
ax = counts.plot(kind='bar', color=['steelblue', 'salmon'])

plt.title('Income Class Distribution')
plt.xlabel('Income')
plt.ylabel('Count')
plt.xticks(rotation=0)

# Adding Count & Pecentage in Each Bar
for bar in ax.patches:
    height = bar.get_height()
    x = bar.get_x() + bar.get_width() / 2
    percentage = (height / total) * 100

    ax.text(
        x,
        height,
        f'{int(height):,}\n({percentage:.1f}%)',
        ha='center',
        va='bottom',
        fontsize=9
    )

plt.tight_layout()
plt.show()


# Plot 2: Age Distribution by Income
plt.figure(figsize=(7, 4))
for label, color in zip(['<=50K', '>50K'], ['steelblue', 'salmon']):
    df[df['income'] == label]['age'].hist(bins=30, alpha=0.6, label=label, color=color)
plt.title('Age Distribution by Income')
plt.xlabel('Age')
plt.ylabel('Count')
plt.legend()
plt.tight_layout()
plt.show()


# Plot 3: Education vs Income rate
edu_order = ['Preschool','1st-4th','5th-6th','7th-8th','9th','10th','11th','12th',
             'HS-grad','Some-college','Assoc-voc','Assoc-acdm','Bachelors','Masters','Prof-school','Doctorate']
edu_rate = df.groupby('education')['income'].apply(lambda x: (x == '>50K').mean() * 100).reindex(edu_order).dropna()

plt.figure(figsize=(8, 5))
edu_rate.plot(kind='barh', color='steelblue')
plt.title('% Earning >$50K by Education Level')
plt.xlabel('% earning >50K')
plt.tight_layout()
plt.show()


# Plot 4: Correlation Heatmap
num_cols = ['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', 'hours-per-week']
plt.figure(figsize=(8, 6))
sns.heatmap(df[num_cols].corr(), annot=True, fmt='.2f', cmap='coolwarm', center=0)
plt.title('Correlation Heatmap')
plt.tight_layout()
plt.show()

# 3. Data Preprocessing

df_clean = df.copy()

# Encode Target Variable Manually for Clarity
df_clean["income"] = df_clean["income"].str.strip()

income_binary = []
for value in df_clean["income"]:
    if value == ">50K":
        income_binary.append(1)
    else:
        income_binary.append(0)

df_clean["income"] = income_binary

# Fill Missing Categorical Values Using Mode
for col in ["workclass", "occupation", "native-country"]:
    df_clean[col] = df_clean[col].fillna(df_clean[col].mode()[0])

# Drop Unnecessary Columns
df_clean = df_clean.drop(columns=["fnlwgt", "education"])

# Encode Categorical Features Using LabelEncoder
label_encoder = LabelEncoder()

for col in df_clean.select_dtypes(include="object").columns:
    df_clean[col] = label_encoder.fit_transform(df_clean[col])

print("Final Feature Set:")
print(df_clean.drop("income", axis=1).columns)

#  4. Train/test split

X = df_clean.drop("income", axis=1)
y = df_clean["income"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

# Scale Features for Models that need it
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 5. Model Training and Evaluation

results = {}

# Logistic Regression
lr = LogisticRegression(max_iter=1000, random_state=42)
lr.fit(X_train_scaled, y_train)

lr_predictions = lr.predict(X_test_scaled)
lr_probabilities = lr.predict_proba(X_test_scaled)[:, 1]

results["Logistic Regression"] = {
    "model": lr,
    "pred": lr_predictions,
    "prob": lr_probabilities
}

# Decision Tree
dt = DecisionTreeClassifier(max_depth=8, random_state=42)
dt.fit(X_train, y_train)

dt_predictions = dt.predict(X_test)
dt_probabilities = dt.predict_proba(X_test)[:, 1]

results["Decision Tree"] = {
    "model": dt,
    "pred": dt_predictions,
    "prob": dt_probabilities
}

# Random Forest
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

rf_predictions = rf.predict(X_test)
rf_probabilities = rf.predict_proba(X_test)[:, 1]

results["Random Forest"] = {
    "model": rf,
    "pred": rf_predictions,
    "prob": rf_probabilities
}

# Gradient Boosting
gb = GradientBoostingClassifier(n_estimators=100, random_state=42)
gb.fit(X_train, y_train)

gb_predictions = gb.predict(X_test)
gb_probabilities = gb.predict_proba(X_test)[:, 1]

results["Gradient Boosting"] = {
    "model": gb,
    "pred": gb_predictions,
    "prob": gb_probabilities
}

# KNN
knn = KNeighborsClassifier(n_neighbors=15)
knn.fit(X_train_scaled, y_train)

knn_predictions = knn.predict(X_test_scaled)
knn_probabilities = knn.predict_proba(X_test_scaled)[:, 1]

results["KNN"] = {
    "model": knn,
    "pred": knn_predictions,
    "prob": knn_probabilities
}

print("\nModel Performance Summary:")

summary_results = {}

for model_name in results:
    y_pred = results[model_name]["pred"]
    y_prob = results[model_name]["prob"]

    acc = accuracy_score(y_test, y_pred)
    auc = roc_auc_score(y_test, y_prob)
    cv_auc = cross_val_score(
        results[model_name]["model"],
        X_train_scaled if model_name in ["Logistic Regression", "KNN"] else X_train,
        y_train,
        cv=5,
        scoring="roc_auc"
    ).mean()

    summary_results[model_name] = {
        "Accuracy": acc,
        "ROC-AUC": auc,
        "CV-AUC": cv_auc
    }

    print(f"\n{model_name}")
    print(f"Accuracy: {acc:.4f}")
    print(f"ROC-AUC: {auc:.4f}")
    print(f"CV ROC-AUC: {cv_auc:.4f}")
    print(classification_report(y_test, y_pred, target_names=["<=50K", ">50K"]))

# 6. Visualize results

# Plot 5: Model comparison
model_names = []
accuracy_scores = []
roc_auc_scores = []

for model_name in summary_results:
    model_names.append(model_name)
    accuracy_scores.append(summary_results[model_name]["Accuracy"])
    roc_auc_scores.append(summary_results[model_name]["ROC-AUC"])

x_positions = np.arange(len(model_names))
bar_width = 0.4

plt.figure(figsize=(10, 5))

plt.bar(
    x_positions - bar_width / 2,
    accuracy_scores,
    bar_width,
    label="Accuracy",
    color="steelblue"
)

plt.bar(
    x_positions + bar_width / 2,
    roc_auc_scores,
    bar_width,
    label="ROC-AUC",
    color="salmon"
)

plt.xticks(x_positions, model_names, rotation=15, ha="right")
plt.ylim(0, 1)
plt.ylabel("Score")
plt.title("Model Performance Comparison")
plt.legend()
plt.tight_layout()
plt.show()

# Plot 6: Confusion Matrix for best model
best_model_name = max(summary_results, key=lambda x: summary_results[x]["ROC-AUC"])
best_model = results[best_model_name]

plt.figure(figsize=(5, 4))
sns.heatmap(
    confusion_matrix(y_test, best_model["pred"]),
    annot=True,
    fmt="d",
    cmap="Blues"
)
plt.title(f"Confusion Matrix - {best_model_name}")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# Plot 7: ROC curves for all models
plt.figure(figsize=(7, 6))
for name, info in results.items():

    fpr, tpr, _ = roc_curve(y_test, info['prob'])
    auc_score = summary_results[name]["ROC-AUC"]
    plt.plot(fpr, tpr, lw=2, label=f"{name} (AUC={auc_score:.3f})")

plt.plot([0, 1], [0, 1], 'k--', label='Random')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curves')
plt.legend(fontsize=8)
plt.tight_layout()
plt.show()

# Plot 8: Feature importance (Random Forest)
rf = results['Random Forest']['model']
feat_imp = pd.Series(rf.feature_importances_, index=X.columns).sort_values()

plt.figure(figsize=(8, 5))
feat_imp.plot(kind='barh', color='steelblue')
plt.title('Feature Importance (Random Forest)')
plt.xlabel('Importance')
plt.tight_layout()
plt.show()

# 7. Summary

print("\n--- Final Results ---")
summary_df = pd.DataFrame(summary_results).T.round(4)
print(summary_df)

print("\nBest Overall Model:", best_model_name)